version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - "> 1.8.1"
  - dependency-name: pytest
    versions:
    - "> 3.2.3"
  - dependency-name: pycodestyle
    versions:
    - 2.6.0
